/* do not change this file, it is auto generated by storybook. */
import { start, updateView, type View } from '@storybook/react-native'

const normalizedStories = [
  {
    titlePrefix: '',
    directory: './src',
    files: '**/*.mdx',
    importPathMatcher: /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.mdx)$/,
    // @ts-expect-error
    req: require.context(
      '../src',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.mdx)$/
    ),
  },
  {
    titlePrefix: '',
    directory: './src',
    files: '**/*.stories.@(js|jsx|mjs|ts|tsx)',
    importPathMatcher:
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|mjs|ts|tsx))$/,
    // @ts-expect-error
    req: require.context(
      '../src',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|mjs|ts|tsx))$/
    ),
  },
  {
    titlePrefix: '',
    directory: '../../packages/ui/src',
    files: '**/*.mdx',
    importPathMatcher: /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.mdx)$/,
    // @ts-expect-error
    req: require.context(
      '../../../packages/ui/src',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.mdx)$/
    ),
  },
  {
    titlePrefix: '',
    directory: '../../packages/ui/src',
    files: '**/*.stories.@(js|jsx|mjs|ts|tsx)',
    importPathMatcher:
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|mjs|ts|tsx))$/,
    // @ts-expect-error
    req: require.context(
      '../../../packages/ui/src',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|mjs|ts|tsx))$/
    ),
  },
]

declare global {
  var view: View
  var STORIES: typeof normalizedStories
}

const annotations = [require('./preview'), require('@storybook/react-native/preview')]

global.STORIES = normalizedStories

// @ts-expect-error
module?.hot?.accept?.()

if (!global.view) {
  global.view = start({
    annotations,
    storyEntries: normalizedStories,
  })
} else {
  updateView(global.view, annotations, normalizedStories)
}

// biome-ignore lint/suspicious/noRedeclare: <explanation>
export const view: View = global.view
