import { StylesProvider } from "./styles-provider";
import { Provider } from "app/provider";
import { LocaleAttribute } from "./locale-attribute";
import "./globals.css";

export const metadata = {
	title: "Create Solito App",
	description: "Generated by create Solito app",
};

export async function generateStaticParams() {
	return [{ lang: 'en' }, { lang: 'fr' }]
}

export default async function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: Promise<{ lang: string }>;
}) {
	const { lang } = await params;
	return (
		<html lang={lang}>
			<body>
				<StylesProvider>
					<Provider locale={lang}>
						<LocaleAttribute />
						{children}
					</Provider>
				</StylesProvider>
			</body>
		</html>
	);
}

